package entidades;
// Generated 23/01/2013 14:28:34 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {
    
    private Integer idCompra;
    private Vendedor vendedor;
    private Cliente cliente;
    private Date data;
    private double total;
    private Set veiculos = new HashSet(0);

    public Compra() {
    }
    
    public Compra(Vendedor vendedor, Cliente cliente, Date data, double total) {
        this.vendedor = vendedor;
        this.cliente = cliente;
        this.data = data;
        this.total = total;
    }
    
    public Compra(Vendedor vendedor, Cliente cliente, Date data, double total, Set veiculos) {
        this.vendedor = vendedor;
        this.cliente = cliente;
        this.data = data;
        this.total = total;
        this.veiculos = veiculos;
    }
    
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }
}