package entidades;
// Generated 17/01/2013 12:55:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Veiculo generated by hbm2java
 */
public class Veiculo  implements java.io.Serializable {


     private Integer idVeiculo;
     private Compra compra;
     private String marca;
     private String cor;
     private String valor;
     private Integer km;
     private String tipo;
     private Set motos = new HashSet(0);
     private Set carros = new HashSet(0);

    public Veiculo() {
    }

	
    public Veiculo(Compra compra, String marca) {
        this.compra = compra;
        this.marca = marca;
    }
    public Veiculo(Compra compra, String marca, String cor, String valor, Integer km, String tipo, Set motos, Set carros) {
       this.compra = compra;
       this.marca = marca;
       this.cor = cor;
       this.valor = valor;
       this.km = km;
       this.tipo = tipo;
       this.motos = motos;
       this.carros = carros;
    }
   
    public Integer getIdVeiculo() {
        return this.idVeiculo;
    }
    
    public void setIdVeiculo(Integer idVeiculo) {
        this.idVeiculo = idVeiculo;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Integer getKm() {
        return this.km;
    }
    
    public void setKm(Integer km) {
        this.km = km;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getMotos() {
        return this.motos;
    }
    
    public void setMotos(Set motos) {
        this.motos = motos;
    }
    public Set getCarros() {
        return this.carros;
    }
    
    public void setCarros(Set carros) {
        this.carros = carros;
    }




}


