/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import javax.swing.JFrame;

/**
 *
 * @author GUSTAVO
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        mCliente = new javax.swing.JMenuItem();
        mVeiculo = new javax.swing.JMenu();
        mCarro = new javax.swing.JMenuItem();
        mMoto = new javax.swing.JMenuItem();
        mVendedor = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFile.setText("File");

        mSair.setText("Sair");
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        menuFile.add(mSair);

        jMenuBar1.add(menuFile);

        menuCadastro.setText("Cadastro");

        mCliente.setText("Cliente");
        mCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(mCliente);

        mVeiculo.setText("Veículo");

        mCarro.setText("Carro");
        mCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCarroActionPerformed(evt);
            }
        });
        mVeiculo.add(mCarro);

        mMoto.setText("Moto");
        mMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMotoActionPerformed(evt);
            }
        });
        mVeiculo.add(mMoto);

        menuCadastro.add(mVeiculo);

        mVendedor.setText("Vendedor");
        mVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVendedorActionPerformed(evt);
            }
        });
        menuCadastro.add(mVendedor);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mSairActionPerformed

    private void mClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mClienteActionPerformed
        JFrame janela = new FormCliente();
        janela.setVisible(true);
    }//GEN-LAST:event_mClienteActionPerformed

    private void mVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVendedorActionPerformed
        JFrame janela = new FormVendedor();
        janela.setVisible(true);
    }//GEN-LAST:event_mVendedorActionPerformed

    private void mCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCarroActionPerformed
        //JFrame janela = new FormCarro();
        //janela.setVisible(true);
    }//GEN-LAST:event_mCarroActionPerformed

    private void mMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMotoActionPerformed
        //JFrame janela = new FormMoto();
        //janela.setVisible(true);
    }//GEN-LAST:event_mMotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mCarro;
    private javax.swing.JMenuItem mCliente;
    private javax.swing.JMenuItem mMoto;
    private javax.swing.JMenuItem mSair;
    private javax.swing.JMenu mVeiculo;
    private javax.swing.JMenuItem mVendedor;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuFile;
    // End of variables declaration//GEN-END:variables
}
